//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutup
{
    using System;
    
    public partial class ComplexType1
    {
        public Nullable<System.DateTime> kaynak_basımtarihi { get; set; }
    }
}
